#!/bin/bash

wget https://cran.r-project.org/src/contrib/Archive/ncdf4/ncdf4_1.13.tar.gz -O ncdf4_1.13.tar.gz
R CMD INSTALL ncdf4_1.13.tar.gz

Rscript -e "install.packages('stringr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('ggplot2', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('dplyr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('tidyr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('gridExtra', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('tmap', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('viridis', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('maps', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('ggmap', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('httr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('sf', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('raster', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('rgdal', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('ranger', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('caret', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('randomForest', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('rlang', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('RFmarkerDetector', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('AUCRF', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('kernlab', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('ROCR', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('MASS', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('glmnet', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('MLmetrics', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('plyr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('lubridate', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('readr', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('rNOMADS', repos='http://cran.us.r-project.org')"
Rscript -e "install.packages('ncdf4', repos='http://cran.us.r-project.org')"
